### ISSUE TITLE
Installation via CocoaPods fails

### ISSUE THREAD

**Issue by repomies** [frankrausch/Typographizer#7]
Tried to install Typographizer via CocoaPods 1.4.0 (by adding `pod 'Typographizer', :git => 'https://github.com/frankrausch/Typographizer.git'`) but got an error message regarding the last item in the podspec:
```
[!] Failed to load 'Typographizer' podspec: 
[!] Invalid `Typographizer.podspec` file: undefined local variable or method `spec' for Pod:Module
Did you mean?  inspect.
```

**Comment by frankrausch** [comment]
Thanks. I don’t use CocoaPods myself, and @syncube kindly created the `.podspec` file for me.
To fix the issue you described, I changed `spec.cocoapods_version` to `s.cocoapods_version` because it looked suspicious. 😬

Please let me know if this fixes the problem. Thank you!

**Comment by repomies** [comment]
Oops, somehow missed your earlier reply, sorry!

Now it finishes the installation but results in an empty folder (containing just LICENSE and README.md). I'd guess the `s.source_files` entry needs to be edited in the podspec to match the actual folder structure of the repo?

**Comment by frankrausch** [comment]
Oh, I see. I would happily merge a PR if you have the time to implement and test this. :)

**Comment by repomies** [comment]
Well lo and behold, this seemed to fix it: https://github.com/frankrausch/Typographizer/pull/9 :)

**Comment by frankrausch** [comment]
Cool! Thanks a lot. Merged.
